/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racunarstvo.java;

import java.io.File;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Attr;
import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Text;

/**
 *
 * @author Matija
 */
public class GUIPanel extends javax.swing.JPanel {

    /**
     * Creates new form GUIPanel
     */
    public GUIPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIme = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtGrad = new javax.swing.JTextField();
        txtProracun = new javax.swing.JTextField();
        txtPredsjednik = new javax.swing.JTextField();
        btnSpremi = new javax.swing.JButton();

        lblIme.setText("Ime");

        jLabel2.setText("Grad");

        jLabel3.setText("Proracun");

        jLabel4.setText("Predsjednik");

        txtIme.setText("TestIme");

        txtGrad.setText("TestGrad");

        txtProracun.setText("Test1234");

        txtPredsjednik.setText("TestPredsjednik");

        btnSpremi.setText("SPREMI XML");
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIme)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnSpremi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtGrad)
                    .addComponent(txtProracun)
                    .addComponent(txtPredsjednik))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIme)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtGrad, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtProracun, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPredsjednik, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSpremi)
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed
        String ime = txtIme.getText();
        String grad = txtGrad.getText();
        String predsjednik = txtPredsjednik.getText();
        String proracun = txtProracun.getText();
        
        DocumentBuilderFactory parserGenerator = DocumentBuilderFactory.newInstance();
        
        try {
            DocumentBuilder xmlGenerator = parserGenerator.newDocumentBuilder();
            DOMImplementation domImplementation = xmlGenerator.getDOMImplementation();
            
            Document noviDokument = null;
            noviDokument = domImplementation.createDocument(null, "klub", null);
            
            Element root = noviDokument.getDocumentElement();
            
            Element klub = noviDokument.createElement("klub");
            Text klubText = noviDokument.createTextNode(ime);
            klub.appendChild(klubText);
            root.appendChild(klub);
            
            Element nodeGrad = noviDokument.createElement("grad");
            Text gradText = noviDokument.createTextNode(grad);
            nodeGrad.appendChild(gradText);
            root.appendChild(nodeGrad);
            
            Element nodePredsjednik = noviDokument.createElement("predsjednik");
            Text predsjednikText = noviDokument.createTextNode(predsjednik);
            nodePredsjednik.appendChild(predsjednikText);
            root.appendChild(nodePredsjednik);
            
            Element nodeProracun = noviDokument.createElement("proracun");
            Text proracunText = noviDokument.createTextNode(proracun);
            nodeProracun.appendChild(proracunText);
            
            Attr testAttr = noviDokument.createAttribute("test");
            testAttr.setNodeValue("testVrijednost");
            nodeProracun.setAttributeNode(testAttr);
            root.appendChild(nodeProracun);
            
            
            TransformerFactory tFactory = TransformerFactory.newInstance();
            Transformer transform = tFactory.newTransformer();
            DOMSource source = new DOMSource(noviDokument);
            
            StreamResult result = new StreamResult(new File("klub.xml"));
            transform.transform(source, result);
            
            System.out.println("The XML file has been created!");
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSpremiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpremi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIme;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPredsjednik;
    private javax.swing.JTextField txtProracun;
    // End of variables declaration//GEN-END:variables
}
