SELECT YEAR(GETDATE()) AS Year,
MONTH(GETDATE()) AS Month,
DAY(GETDATE()) AS Day,
DATEPART(week, GETDATE()) AS Week

SELECT DATEADD(year, 11, GETDATE()),
DATEADD(day, 1282, GETDATE()),
DATEADD(month, 37, GETDATE())

SELECT DATEDIFF(day, '1995-01-18', GETDATE()) AS Days,
DATEDIFF(month, '1995-01-18', GETDATE()) AS Months,
DATEDIFF(year, '1995-01-18', GETDATE()) AS Years,
DATEDIFF(minute, '1995-01-18', GETDATE()) AS Minutes