//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaKrava
{
    using System;
    using System.Collections.Generic;
    
    public partial class Krava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Krava()
        {
            this.ProizvodnaMlijekas = new HashSet<ProizvodnaMlijeka>();
        }
    
        public int ID { get; set; }
        public string Ime { get; set; }
        public Nullable<int> Pasmina { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string VeterinarskiBroj { get; set; }
        public int BrojTeladi { get; set; }
    
        public virtual Pasmina Pasmina1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProizvodnaMlijeka> ProizvodnaMlijekas { get; set; }
    }
}
