//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaKrava
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProizvodnaMlijeka
    {
        public int ID { get; set; }
        public int KravaID { get; set; }
        public System.DateTime Datum { get; set; }
        public int KolicinaMlijeka { get; set; }
        public double ProsjecniPostotakMasnoce { get; set; }
        public double ProsjecniPostotakMikroorganizama { get; set; }
    
        public virtual Krava Krava { get; set; }
    }
}
