//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod08
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumraEntities : DbContext
    {
        public HumraEntities()
            : base("name=HumraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Drzava> Drzavas { get; set; }
        public DbSet<Grad> Grads { get; set; }
        public DbSet<Kategorija> Kategorijas { get; set; }
        public DbSet<Komercijalist> Komercijalists { get; set; }
        public DbSet<KreditnaKartica> KreditnaKarticas { get; set; }
        public DbSet<Kupac> Kupacs { get; set; }
        public DbSet<Potkategorija> Potkategorijas { get; set; }
        public DbSet<Proizvod> Proizvods { get; set; }
        public DbSet<Racun> Racuns { get; set; }
        public DbSet<Stavka> Stavkas { get; set; }
    }
}
