//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod08
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorija
    {
        public Kategorija()
        {
            this.Potkategorijas = new HashSet<Potkategorija>();
        }
    
        public int IDKategorija { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Potkategorija> Potkategorijas { get; set; }
    }
}
