//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod08
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komercijalist
    {
        public Komercijalist()
        {
            this.Racuns = new HashSet<Racun>();
        }
    
        public int IDKomercijalist { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<bool> StalniZaposlenik { get; set; }
    
        public virtual ICollection<Racun> Racuns { get; set; }
    }
}
