//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod08
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupac
    {
        public Kupac()
        {
            this.Racuns = new HashSet<Racun>();
        }
    
        public int IDKupac { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> GradID { get; set; }
    
        public virtual Grad Grad { get; set; }
        public virtual ICollection<Racun> Racuns { get; set; }
    }
}
