//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod08
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potkategorija
    {
        public Potkategorija()
        {
            this.Proizvods = new HashSet<Proizvod>();
        }
    
        public int IDPotkategorija { get; set; }
        public int KategorijaID { get; set; }
        public string Naziv { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        public virtual ICollection<Proizvod> Proizvods { get; set; }
    }
}
