//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod08
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        public Proizvod()
        {
            this.Stavkas = new HashSet<Stavka>();
        }
    
        public int IDProizvod { get; set; }
        public string Naziv { get; set; }
        public string BrojProizvoda { get; set; }
        public string Boja { get; set; }
        public short MinimalnaKolicinaNaSkladistu { get; set; }
        public decimal CijenaBezPDV { get; set; }
        public Nullable<int> PotkategorijaID { get; set; }
    
        public virtual Potkategorija Potkategorija { get; set; }
        public virtual ICollection<Stavka> Stavkas { get; set; }
    }
}
