//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod08
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public Racun()
        {
            this.Stavkas = new HashSet<Stavka>();
        }
    
        public int IDRacun { get; set; }
        public System.DateTime DatumIzdavanja { get; set; }
        public string BrojRacuna { get; set; }
        public int KupacID { get; set; }
        public Nullable<int> KomercijalistID { get; set; }
        public Nullable<int> KreditnaKarticaID { get; set; }
        public string Komentar { get; set; }
    
        public virtual Komercijalist Komercijalist { get; set; }
        public virtual KreditnaKartica KreditnaKartica { get; set; }
        public virtual Kupac Kupac { get; set; }
        public virtual ICollection<Stavka> Stavkas { get; set; }
    }
}
