/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racunarstvo.java;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Time;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Matija
 */
public class Dokumenti extends javax.swing.JFrame {

    public volatile boolean flag;
    
    /**
     * Creates new form Dokumenti
     */
    public Dokumenti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPath = new javax.swing.JTextField();
        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPath.setText("C:\\\\JavaTest\\\\");

            btnPokreni.setText("Pokreni");
            btnPokreni.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPokreniActionPerformed(evt);
                }
            });

            btnZaustavi.setText("Zaustavi");
            btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnZaustaviActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPath)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnPokreni)
                            .addGap(18, 18, 18)
                            .addComponent(btnZaustavi)
                            .addGap(0, 213, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPokreni)
                        .addComponent(btnZaustavi))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        final String folderPath = txtPath.getText();
        final Random r = new Random();
        flag = true;
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                while(flag) {
                    stvoriFile(folderPath, r);
                    sleepyTime();
                    brisiNajstarijiFile(folderPath);
                }
            }

            private void stvoriFile(String folderPath, Random r) {
                folderPath += r.nextInt(100) + ".txt";
                Path path = Paths.get(folderPath);
                
                
                if(Files.notExists(path)) {
                    try {
                      Files.createFile(path);
                    }
                    catch (IOException ex) {
                        Logger.getLogger(Dokumenti.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            private void sleepyTime() {
                try {
                    Thread.sleep(1000);
                }
                catch (InterruptedException ex) {
                    Logger.getLogger(Dokumenti.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            private void brisiNajstarijiFile(String folderPath) {
                File dir = new File(folderPath);
                File[] files = dir.listFiles();
                if(files == null || files.length == 0) {
                    
                }
                else {
                    File lastModified = files[0];
                    
                    for(int i = 0; i < files.length; i++) {
                        if(lastModified.lastModified() < files[i].lastModified()) {
                            lastModified = files[i];
                        }
                    }
                    
                    lastModified.delete();
                }
            }
        }).start();
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        flag = false;
    }//GEN-LAST:event_btnZaustaviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokumenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokumenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokumenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokumenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokumenti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
